# Generated by Django 3.1.6 on 2021-02-12 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tesla_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryName1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TeslaModel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teslamodels', to='tesla_data.countryname1')),
            ],
        ),
        migrations.DeleteModel(
            name='CountryName',
        ),
        migrations.DeleteModel(
            name='TeslaModel',
        ),
    ]
